version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://api.yourstyle.dcreativo.ch
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
    - MONGODB_URI=${MONGODB_URI}
    - JWT_SECRET=${JWT_SECRET}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
    - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
